### ISSUE TITLE
Sentinel 5P

### ISSUE THREAD

**Issue by c1p81** [anikfal/GIS_solutions#1]
i can't set the sentinel 5 collection (sentinel 2 it's ok)
Any suggestions?
Thanks for your work
L

**Comment by anikfal** [comment]
How did you set it to Sentinel 5?
Did you set `data_collection = SENTINEL-5`?

**Comment by c1p81** [comment]
yes 
start_date = f"{inp.start_year}-{format(inp.start_month, '02d')}-{format(inp.start_day, '02d')}T{format(inp.start_hour, '02d')}:00:00.000Z"
end_date = f"{inp.end_year}-{format(inp.end_month, '02d')}-{format(inp.end_day, '02d')}T{format(inp.end_hour, '02d')}:00:00.000Z"
data_collection = "SENTINEL-5"

the error is
Traceback (most recent call last):
  File "/home/luca/gis_solutions/sentinel_download_new_api/sentinel_download.py", line 59, in <module>
    lookedup_tiles = json['value']

seems no json file available
the user_inputs.py are ok
everything works fine with same settings and collection Sentinel 2

Thanks
L

**Comment by anikfal** [comment]
Did you provide `points_coordinates.csv`?
